### ISSUE TITLE
Security: DON'T EVER EXPOSE SENSITIVE DATA

### ISSUE THREAD

**Issue by jeffque** [GeoSales-Evolution/multi-tenant-uploader#27]
Token identifies an individual. Does not expose it in the URL as in this excerpt:

```ts
app.post('/upload/:token/:tenant', (req: express.Request, res: express.Response) => {
```

It shall be a header. Normally an `Authorization: Bearer` suffices. One could also try to use a JWT where all relevant data would be in the token, like whoami and whatever, but for it to be really really great it should be stateless (ie, time to live should be ridiculously small).

**Comment by uxjp** [comment]
I'm on it. It's my priority right now.

**Comment by uxjp** [comment]
#28 closes the issue
